import type { Level } from './content';

/** Side discoveries add witnesses without revealing later quest solutions. */
export const activityDiscoveries: Record<string, { level: Level; title: string; text: string; lead: string }> = {
  'cafe:A1': { level:'A1', title:'A place set for nobody', text:'Your customers leave fed and understood. While clearing the trays, Marta notices that the empty table has used a spoon. Its receipt carries the impression of a brass stamp, but no destination.', lead:'Marta keeps the spoon beside her kettle. Something passed through the café without leaving its name.' },
  'market:A1': { level:'A1', title:'An honest weight', text:'The shopping is settled and the change is right. Fritz finds a second set of weights in a delivery sack. They match his own exactly, except each has a tiny railway symbol underneath.', lead:'The market received goods from somewhere the official timetable cannot reach.' },
  'detective:A1': { level:'A1', title:'The witness between the lines', text:'Your evidence puts an ordinary sequence back in order. Ada notices the same correction mark on two unrelated records. Whoever changed them wanted the events to look like a coincidence.', lead:'Keep checking dates and witnesses. A missing name can still leave a pattern.' },
  'delivery:A1': { level:'A1', title:'A letter that made it home', text:'The route is understood and the parcel reaches its intended place. Lina compares its address with an old delivery label. Both give directions around a platform the town has stopped mentioning.', lead:'An address is more than a line in a register. Someone still knows how to get there.' },
  'cafe:A2': { level:'A2', title:'The customer who ordered twice', text:'Your shift ends with the right orders and a small argument about the kettle. One guest insists they already ate this meal. Marta’s clock has recorded two payments at the same minute.', lead:'The lost hour is repeating small things as well as large ones.' },
  'market:A2': { level:'A2', title:'Tomorrow’s shopping', text:'The basket balances and nobody is short-changed. Greta finds that the rest garden’s supplier wrote a delivery date that has not happened yet. The herbs themselves are perfectly ordinary, to her considerable relief.', lead:'The records of the missing hour disagree with what people can hold in their hands.' },
  'detective:A2': { level:'A2', title:'A correction with a different hand', text:'The evidence supports a sequence instead of a convenient accusation. Ada recognises an alteration made after the original closure. Its handwriting belongs to a clerk, not the person who signed the page.', lead:'Find what the original order actually permitted before deciding who benefited.' },
  'delivery:A2': { level:'A2', title:'Directions that survived', text:'The delivery instructions work even where the road signs disagree. Lina’s route notebook retains a turn removed from the archive map. Someone taught the couriers the real route before it vanished.', lead:'Follow practical knowledge toward Nebelstadt; the official records are only one witness.' },
  'cafe:B1': { level:'B1', title:'One table, several accounts', text:'You manage the orders without making the customers agree about everything. Their disagreement leaves a useful detail: the lighthouse signal was seen from two places, but described in different ways.', lead:'A contradiction can come from a viewpoint. Ask what each witness could actually see.' },
  'market:B1': { level:'B1', title:'The price of a route', text:'The trade works for both sides. Fritz writes the cost of the shorter crossing beside the benefits of the longer one. The comparison gives the council something more useful than a slogan.', lead:'A workable agreement must acknowledge the people who bear its costs.' },
  'detective:B1': { level:'B1', title:'An explanation that fits', text:'You distinguish what the evidence shows from what a witness assumes. Ada preserves both statements instead of throwing away the inconvenient one. The repair ledger can now be compared with a defensible timeline.', lead:'Bring the accounts together; certainty should come from evidence, not a hurried accusation.' },
  'delivery:B1': { level:'B1', title:'An answer from the other end', text:'The directions get the message through. The reply arrives with a small warm pulse from Waldruh. A route that carries an answer feels quite different from a route that only carries orders.', lead:'The Atlas listens for agreement in both directions.' },
};
