import type { PlacedScenerySpec } from './placed-scenery';

// Independent sprites use foot positions on the 1536 × 1024 harbor terrain.
// Leave the stair aprons, NPC stops and learning-object approaches open.
export const nebelstadtPlacements: readonly PlacedScenerySpec[] = [
  { id: 'nebelstadt-council-archive', asset: 'archive', x: 264, y: 309, width: 426, motion: 'building' },
  { id: 'nebelstadt-observatory-building', asset: 'cafe', x: 743, y: 254, width: 235, motion: 'building' },
  { id: 'nebelstadt-railway-station', asset: 'station', x: 1091, y: 295, width: 375, motion: 'building' },
  { id: 'nebelstadt-shipwright-workshop', asset: 'workshop', x: 273, y: 727, width: 355, motion: 'building' },
  { id: 'nebelstadt-east-lighthouse', asset: 'house', x: 1436, y: 398, width: 250, motion: 'building' },
  { id: 'nebelstadt-glass-conservatory', asset: 'greenhouse', x: 1062, y: 848, width: 310, motion: 'building' },
  { id: 'nebelstadt-market-canopy', asset: 'stall', frame: 'stall-1', variant: true, x: 646, y: 773, width: 225, motion: 'cloth' },
  { id: 'nebelstadt-west-cafe-canopy', asset: 'stall', frame: 'stall-2', variant: true, x: 141, y: 435, width: 92, motion: 'cloth' },
  { id: 'nebelstadt-market-north-stall', asset: 'stall', frame: 'stall-3', variant: true, x: 629, y: 653, width: 119, motion: 'cloth', flipX: true },
  { id: 'nebelstadt-garden-gateway', asset: 'arch', x: 1157, y: 471, width: 182, motion: 'building' },
  { id: 'nebelstadt-atlas-armillary', asset: 'fountain', x: 742, y: 479, width: 103, motion: 'building' },

  { id: 'nebelstadt-council-noticeboard', asset: 'sign', x: 390, y: 439, width: 86, motion: 'still' },
  { id: 'nebelstadt-harbor-route-board', asset: 'sign', x: 968, y: 289, width: 54, motion: 'still' },
  { id: 'nebelstadt-station-board', asset: 'sign', x: 1212, y: 315, width: 50, motion: 'still' },

  { id: 'nebelstadt-council-north-tree', asset: 'tree', frame: 'tree-1', variant: true, x: 42, y: 134, width: 122, motion: 'tree' },
  { id: 'nebelstadt-archive-west-tree', asset: 'tree', frame: 'tree-2', variant: true, x: 89, y: 270, width: 98, motion: 'tree' },
  { id: 'nebelstadt-archive-east-tree', asset: 'tree', frame: 'tree-3', variant: true, x: 552, y: 162, width: 104, motion: 'tree' },
  { id: 'nebelstadt-archive-terrace-tree', asset: 'tree', frame: 'tree-4', variant: true, x: 550, y: 326, width: 76, motion: 'tree' },
  { id: 'nebelstadt-west-frontage-tree', asset: 'tree', x: 220, y: 444, width: 95, motion: 'tree' },
  { id: 'nebelstadt-observatory-east-tree', asset: 'tree', frame: 'tree-2', variant: true, x: 877, y: 213, width: 110, motion: 'tree' },
  { id: 'nebelstadt-station-garden-tree', asset: 'tree', frame: 'tree-3', variant: true, x: 830, y: 353, width: 71, motion: 'tree' },
  { id: 'nebelstadt-station-north-tree', asset: 'tree', frame: 'tree-4', variant: true, x: 1149, y: 148, width: 98, motion: 'tree' },
  { id: 'nebelstadt-east-garden-tree', asset: 'tree', frame: 'tree-1', variant: true, x: 996, y: 394, width: 90, motion: 'tree' },
  { id: 'nebelstadt-west-waterfront-tree', asset: 'tree', x: 27, y: 555, width: 100, motion: 'tree' },
  { id: 'nebelstadt-workshop-east-tree', asset: 'tree', frame: 'tree-3', variant: true, x: 452, y: 658, width: 104, motion: 'tree' },
  { id: 'nebelstadt-workshop-north-tree', asset: 'tree', frame: 'tree-4', variant: true, x: 350, y: 566, width: 88, motion: 'tree' },
  { id: 'nebelstadt-market-east-tree', asset: 'tree', frame: 'tree-1', variant: true, x: 826, y: 695, width: 92, motion: 'tree' },
  { id: 'nebelstadt-conservatory-west-tree', asset: 'tree', frame: 'tree-2', variant: true, x: 862, y: 811, width: 100, motion: 'tree' },
  { id: 'nebelstadt-conservatory-east-tree', asset: 'tree', x: 1220, y: 787, width: 78, motion: 'tree' },
  { id: 'nebelstadt-harbor-southwest-tree', asset: 'tree', frame: 'tree-4', variant: true, x: 32, y: 963, width: 147, motion: 'tree' },

  { id: 'nebelstadt-archive-west-cypress', asset: 'cypress', x: 189, y: 279, width: 42, motion: 'tree' },
  { id: 'nebelstadt-archive-front-cypress', asset: 'cypress', x: 342, y: 304, width: 46, motion: 'tree' },
  { id: 'nebelstadt-archive-east-cypress', asset: 'cypress', x: 506, y: 264, width: 50, motion: 'tree' },
  { id: 'nebelstadt-observatory-west-cypress', asset: 'cypress', x: 603, y: 143, width: 40, motion: 'tree' },
  { id: 'nebelstadt-observatory-east-cypress', asset: 'cypress', x: 884, y: 258, width: 49, motion: 'tree' },
  { id: 'nebelstadt-station-side-cypress', asset: 'cypress', x: 934, y: 283, width: 39, motion: 'tree' },
  { id: 'nebelstadt-bridge-garden-cypress', asset: 'cypress', x: 1208, y: 382, width: 44, motion: 'tree' },
  { id: 'nebelstadt-lighthouse-cypress', asset: 'cypress', x: 1325, y: 422, width: 41, motion: 'tree' },
  { id: 'nebelstadt-conservatory-north-cypress', asset: 'cypress', x: 966, y: 640, width: 44, motion: 'tree' },
  { id: 'nebelstadt-conservatory-west-cypress', asset: 'cypress', x: 934, y: 781, width: 46, motion: 'tree' },
  { id: 'nebelstadt-conservatory-east-cypress', asset: 'cypress', x: 1146, y: 849, width: 54, motion: 'tree' },
  { id: 'nebelstadt-conservatory-south-cypress', asset: 'cypress', x: 1033, y: 894, width: 45, motion: 'tree' },

  { id: 'nebelstadt-archive-west-lamp', asset: 'lamp', x: 146, y: 280, width: 21, motion: 'lamp' },
  { id: 'nebelstadt-archive-door-lamp', asset: 'lamp', x: 395, y: 295, width: 20, motion: 'lamp' },
  { id: 'nebelstadt-archive-east-lamp', asset: 'lamp', x: 524, y: 352, width: 20, motion: 'lamp' },
  { id: 'nebelstadt-council-steps-lamp', asset: 'lamp', x: 448, y: 419, width: 28, motion: 'lamp' },
  { id: 'nebelstadt-west-frontage-lamp', asset: 'lamp', x: 55, y: 433, width: 29, motion: 'lamp' },
  { id: 'nebelstadt-cafe-front-lamp', asset: 'lamp', x: 246, y: 477, width: 27, motion: 'lamp' },
  { id: 'nebelstadt-observatory-west-lamp', asset: 'lamp', x: 637, y: 319, width: 20, motion: 'lamp' },
  { id: 'nebelstadt-observatory-front-lamp', asset: 'lamp', x: 693, y: 279, width: 17, motion: 'lamp' },
  { id: 'nebelstadt-observatory-east-lamp', asset: 'lamp', x: 821, y: 286, width: 18, motion: 'lamp' },
  { id: 'nebelstadt-station-lamp', asset: 'lamp', x: 1071, y: 296, width: 20, motion: 'lamp' },
  { id: 'nebelstadt-east-square-lamp', asset: 'lamp', x: 914, y: 391, width: 21, motion: 'lamp' },
  { id: 'nebelstadt-east-garden-lamp', asset: 'lamp', x: 1080, y: 448, width: 24, motion: 'lamp' },
  { id: 'nebelstadt-signal-bridge-lamp', asset: 'lamp', x: 1280, y: 467, width: 21, motion: 'lamp' },
  { id: 'nebelstadt-lighthouse-lamp', asset: 'lamp', x: 1397, y: 407, width: 20, motion: 'lamp' },
  { id: 'nebelstadt-lower-bridge-lamp', asset: 'lamp', x: 1119, y: 566, width: 22, motion: 'lamp' },
  { id: 'nebelstadt-bridge-mid-lamp', asset: 'lamp', x: 1272, y: 574, width: 18, motion: 'lamp' },
  { id: 'nebelstadt-bridge-south-lamp', asset: 'lamp', x: 1153, y: 631, width: 20, motion: 'lamp' },
  { id: 'nebelstadt-bridge-east-lamp', asset: 'lamp', x: 1452, y: 757, width: 25, motion: 'lamp' },
  { id: 'nebelstadt-workshop-front-lamp', asset: 'lamp', x: 328, y: 745, width: 29, motion: 'lamp' },
  { id: 'nebelstadt-workshop-stairs-lamp', asset: 'lamp', x: 432, y: 762, width: 24, motion: 'lamp' },
  { id: 'nebelstadt-market-stairs-lamp', asset: 'lamp', x: 566, y: 608, width: 20, motion: 'lamp' },
  { id: 'nebelstadt-market-front-lamp', asset: 'lamp', x: 634, y: 812, width: 31, motion: 'lamp' },
  { id: 'nebelstadt-conservatory-west-lamp', asset: 'lamp', x: 849, y: 709, width: 27, motion: 'lamp' },
  { id: 'nebelstadt-conservatory-south-lamp', asset: 'lamp', x: 846, y: 950, width: 26, motion: 'lamp' },
  { id: 'nebelstadt-conservatory-dock-lamp', asset: 'lamp', x: 965, y: 938, width: 22, motion: 'lamp' },
  { id: 'nebelstadt-southwest-dock-lamp', asset: 'lamp', x: 307, y: 856, width: 28, motion: 'lamp' },
  { id: 'nebelstadt-southstairs-west-lamp', asset: 'lamp', x: 441, y: 891, width: 23, motion: 'lamp' },

  { id: 'nebelstadt-square-north-planter', asset: 'planter', frame: 'planter-1', variant: true, x: 637, y: 398, width: 53, motion: 'tree' },
  { id: 'nebelstadt-square-west-planter', asset: 'planter', frame: 'planter-2', variant: true, x: 537, y: 526, width: 55, motion: 'tree' },
  { id: 'nebelstadt-square-south-planter', asset: 'planter', frame: 'garden-1', variant: true, x: 712, y: 584, width: 59, motion: 'still' },
  { id: 'nebelstadt-square-east-planter', asset: 'planter', frame: 'garden-2', variant: true, x: 952, y: 508, width: 56, motion: 'still' },
  { id: 'nebelstadt-conservatory-north-planter', asset: 'planter', frame: 'planter-1', variant: true, x: 932, y: 580, width: 50, motion: 'tree' },
  { id: 'nebelstadt-board-planter', asset: 'planter', frame: 'planter-2', variant: true, x: 454, y: 467, width: 43, motion: 'tree' },
  { id: 'nebelstadt-observatory-door-planter', asset: 'planter', frame: 'garden-1', variant: true, x: 660, y: 261, width: 43, motion: 'still' },
  { id: 'nebelstadt-archive-front-planter', asset: 'planter', frame: 'garden-2', variant: true, x: 282, y: 333, width: 51, motion: 'still' },
  { id: 'nebelstadt-market-east-planter', asset: 'planter', frame: 'planter-1', variant: true, x: 770, y: 798, width: 61, motion: 'tree' },
  { id: 'nebelstadt-conservatory-south-planter', asset: 'planter', frame: 'planter-2', variant: true, x: 1178, y: 887, width: 64, motion: 'tree' },
  { id: 'nebelstadt-conservatory-west-planter', asset: 'planter', frame: 'garden-1', variant: true, x: 891, y: 936, width: 54, motion: 'still' },
  { id: 'nebelstadt-workshop-west-planter', asset: 'planter', frame: 'garden-2', variant: true, x: 53, y: 704, width: 57, motion: 'still' },

  { id: 'nebelstadt-archive-terrace-bench', asset: 'bench', x: 577, y: 344, width: 56, motion: 'still' },
  { id: 'nebelstadt-west-cafe-bench', asset: 'bench', x: 285, y: 469, width: 49, motion: 'still' },
  { id: 'nebelstadt-board-side-bench', asset: 'bench', x: 481, y: 479, width: 49, motion: 'still' },
  { id: 'nebelstadt-station-garden-bench', asset: 'bench', x: 859, y: 377, width: 55, motion: 'still' },
  { id: 'nebelstadt-market-east-bench', asset: 'bench', x: 829, y: 705, width: 50, motion: 'still' },
  { id: 'nebelstadt-conservatory-south-bench', asset: 'bench', x: 1074, y: 910, width: 61, motion: 'still' },
  { id: 'nebelstadt-conservatory-west-bench', asset: 'bench', x: 894, y: 779, width: 53, motion: 'still' },

  { id: 'nebelstadt-west-fishing-boat', asset: 'boat', x: 44, y: 841, width: 97, motion: 'boat' },
  { id: 'nebelstadt-southwest-fishing-boat', asset: 'boat', x: 130, y: 964, width: 112, motion: 'boat', flipX: true },
  { id: 'nebelstadt-conservatory-fishing-boat', asset: 'boat', x: 1223, y: 1000, width: 166, motion: 'boat' },
  { id: 'nebelstadt-east-harbor-boat', asset: 'boat', x: 1488, y: 963, width: 116, motion: 'boat', flipX: true },
];
