import type { PlacedScenerySpec } from './placed-scenery';

// Foot anchors follow the original terraces. Roads, resident routes and quest
// approaches stay open while every tree, lamp and building is a separate asset.
export const waldruhPlacements: readonly PlacedScenerySpec[] = [
  { id: 'waldruh-inn', asset: 'cafe', x: 320, y: 324, width: 390, motion: 'building' },
  { id: 'waldruh-station', asset: 'station', x: 1112, y: 290, width: 396, motion: 'building' },
  { id: 'waldruh-clockmill', asset: 'workshop', x: 1215, y: 557, width: 294, motion: 'building' },
  { id: 'waldruh-west-workshop', asset: 'workshop', frame: 'house-1', variant: true, x: 236, y: 692, width: 328, motion: 'building' },
  { id: 'waldruh-archive', asset: 'archive', x: 543, y: 145, width: 134, motion: 'building' },
  { id: 'waldruh-north-chapel', asset: 'archive', x: 837, y: 123, width: 145, motion: 'building' },
  { id: 'waldruh-east-cottage', asset: 'house', frame: 'house-1', variant: true, x: 1310, y: 142, width: 117, motion: 'building' },
  { id: 'waldruh-north-cottage', asset: 'house', frame: 'house-2', variant: true, x: 446, y: 118, width: 128, motion: 'building' },
  { id: 'waldruh-conservatory', asset: 'greenhouse', x: 1115, y: 849, width: 268, motion: 'building' },

  { id: 'waldruh-plaza-fountain', asset: 'fountain', x: 722, y: 477, width: 142, motion: 'water' },
  { id: 'waldruh-market-west', asset: 'stall', frame: 'stall-1', variant: true, x: 625, y: 724, width: 145, motion: 'cloth' },
  { id: 'waldruh-market-east', asset: 'stall', frame: 'stall-2', variant: true, x: 829, y: 721, width: 154, motion: 'cloth' },
  { id: 'waldruh-market-south', asset: 'stall', frame: 'stall-3', variant: true, x: 756, y: 788, width: 158, motion: 'cloth' },
  { id: 'waldruh-garden-arch', asset: 'arch', x: 955, y: 816, width: 127, motion: 'cloth' },
  { id: 'waldruh-housing-board', asset: 'sign', x: 584, y: 384, width: 58, motion: 'still' },
  { id: 'waldruh-route-board', asset: 'sign', x: 960, y: 326, width: 48, motion: 'still' },
  { id: 'waldruh-archive-board', asset: 'sign', x: 294, y: 865, width: 44, motion: 'still' },
  { id: 'waldruh-river-boat-north', asset: 'boat', x: 1476, y: 208, width: 64, motion: 'boat' },
  { id: 'waldruh-river-boat-south', asset: 'boat', x: 1422, y: 767, width: 82, motion: 'boat', flipX: true },

  { id: 'waldruh-inn-lamp', asset: 'lamp', x: 353, y: 403, width: 22, motion: 'lamp' },
  { id: 'waldruh-west-garden-lamp', asset: 'lamp', x: 170, y: 395, width: 22, motion: 'lamp' },
  { id: 'waldruh-board-west-lamp', asset: 'lamp', x: 628, y: 305, width: 20, motion: 'lamp' },
  { id: 'waldruh-board-east-lamp', asset: 'lamp', x: 648, y: 327, width: 20, motion: 'lamp' },
  { id: 'waldruh-north-garden-lamp', asset: 'lamp', x: 845, y: 359, width: 23, motion: 'lamp' },
  { id: 'waldruh-station-lamp', asset: 'lamp', x: 1064, y: 315, width: 23, motion: 'lamp' },
  { id: 'waldruh-workshop-lamp', asset: 'lamp', x: 492, y: 586, width: 28, motion: 'lamp' },
  { id: 'waldruh-mill-road-lamp', asset: 'lamp', x: 947, y: 574, width: 27, motion: 'lamp' },
  { id: 'waldruh-market-lamp', asset: 'lamp', x: 542, y: 795, width: 27, motion: 'lamp' },
  { id: 'waldruh-east-bridge-lamp', asset: 'lamp', x: 1397, y: 634, width: 28, motion: 'lamp' },
  { id: 'waldruh-conservatory-lamp', asset: 'lamp', x: 1024, y: 945, width: 29, motion: 'lamp' },
  { id: 'waldruh-north-path-lamp', asset: 'lamp', x: 646, y: 192, width: 19, motion: 'lamp' },

  { id: 'waldruh-inn-planter', asset: 'planter', frame: 'planter-1', variant: true, x: 494, y: 375, width: 42, motion: 'tree' },
  { id: 'waldruh-inn-step-planter', asset: 'planter', frame: 'planter-2', variant: true, x: 347, y: 333, width: 30, motion: 'tree' },
  { id: 'waldruh-inn-west-planter', asset: 'planter', frame: 'garden-1', variant: true, x: 121, y: 324, width: 28, motion: 'still' },
  { id: 'waldruh-station-planter-west', asset: 'planter', frame: 'garden-2', variant: true, x: 913, y: 290, width: 30, motion: 'still' },
  { id: 'waldruh-station-planter-east', asset: 'planter', frame: 'planter-1', variant: true, x: 1289, y: 280, width: 28, motion: 'tree' },
  { id: 'waldruh-fountain-planter-west', asset: 'planter', frame: 'planter-2', variant: true, x: 629, y: 469, width: 37, motion: 'tree' },
  { id: 'waldruh-fountain-planter-east', asset: 'planter', frame: 'garden-1', variant: true, x: 796, y: 484, width: 38, motion: 'still' },
  { id: 'waldruh-fountain-planter-north', asset: 'planter', frame: 'garden-2', variant: true, x: 785, y: 414, width: 29, motion: 'still' },
  { id: 'waldruh-market-road-planter', asset: 'planter', frame: 'planter-1', variant: true, x: 494, y: 768, width: 41, motion: 'tree' },
  { id: 'waldruh-market-step-planter', asset: 'planter', frame: 'planter-2', variant: true, x: 592, y: 806, width: 34, motion: 'tree' },
  { id: 'waldruh-west-workshop-planter', asset: 'planter', frame: 'garden-1', variant: true, x: 419, y: 693, width: 36, motion: 'still' },
  { id: 'waldruh-clockmill-planter', asset: 'planter', frame: 'garden-2', variant: true, x: 1084, y: 530, width: 39, motion: 'still' },
  { id: 'waldruh-east-bridge-planter', asset: 'planter', frame: 'planter-1', variant: true, x: 1435, y: 679, width: 40, motion: 'tree' },
  { id: 'waldruh-herb-garden-planter', asset: 'planter', frame: 'planter-2', variant: true, x: 1017, y: 833, width: 39, motion: 'tree' },
  { id: 'waldruh-conservatory-planter-west', asset: 'planter', frame: 'garden-1', variant: true, x: 1009, y: 882, width: 37, motion: 'still' },
  { id: 'waldruh-conservatory-planter-east', asset: 'planter', frame: 'garden-2', variant: true, x: 1264, y: 827, width: 37, motion: 'still' },
  { id: 'waldruh-archive-planter', asset: 'planter', frame: 'planter-1', variant: true, x: 264, y: 905, width: 34, motion: 'tree' },
  { id: 'waldruh-north-square-bench', asset: 'bench', x: 789, y: 356, width: 74, motion: 'still' },
  { id: 'waldruh-fountain-bench', asset: 'bench', x: 644, y: 494, width: 73, motion: 'still' },
  { id: 'waldruh-inn-garden-bench', asset: 'bench', x: 277, y: 420, width: 65, motion: 'still' },
  { id: 'waldruh-west-garden-bench', asset: 'bench', x: 238, y: 846, width: 72, motion: 'still' },
  { id: 'waldruh-herb-garden-bench', asset: 'bench', x: 1061, y: 863, width: 76, motion: 'still' },
  { id: 'waldruh-river-bench', asset: 'bench', x: 1473, y: 616, width: 65, motion: 'still' },

  { id: 'waldruh-square-autumn-tree', asset: 'tree', frame: 'tree-1', variant: true, x: 758, y: 251, width: 189, motion: 'tree' },
  { id: 'waldruh-clockmill-autumn-tree', asset: 'tree', frame: 'tree-2', variant: true, x: 1001, y: 476, width: 132, motion: 'tree' },
  { id: 'waldruh-workshop-autumn-tree', asset: 'tree', frame: 'tree-3', variant: true, x: 428, y: 511, width: 104, motion: 'tree' },
  { id: 'waldruh-south-route-fir', asset: 'cypress', x: 386, y: 872, width: 74, motion: 'tree' },
  { id: 'waldruh-north-tree-01', asset: 'tree', frame: 'tree-4', variant: true, x: 41, y: 119, width: 147, motion: 'tree' },
  { id: 'waldruh-north-tree-02', asset: 'tree', x: 136, y: 105, width: 134, motion: 'tree', flipX: true },
  { id: 'waldruh-north-tree-03', asset: 'cypress', x: 230, y: 73, width: 108, motion: 'tree' },
  { id: 'waldruh-north-tree-04', asset: 'tree', frame: 'tree-2', variant: true, x: 336, y: 72, width: 137, motion: 'tree' },
  { id: 'waldruh-north-tree-05', asset: 'tree', frame: 'tree-3', variant: true, x: 596, y: 85, width: 139, motion: 'tree', flipX: true },
  { id: 'waldruh-north-tree-06', asset: 'tree', frame: 'tree-4', variant: true, x: 685, y: 123, width: 147, motion: 'tree' },
  { id: 'waldruh-north-tree-07', asset: 'cypress', x: 924, y: 113, width: 125, motion: 'tree' },
  { id: 'waldruh-north-tree-08', asset: 'tree', frame: 'tree-1', variant: true, x: 1004, y: 91, width: 138, motion: 'tree', flipX: true },
  { id: 'waldruh-north-tree-09', asset: 'cypress', x: 1152, y: 84, width: 120, motion: 'tree' },
  { id: 'waldruh-north-tree-10', asset: 'tree', x: 1435, y: 132, width: 130, motion: 'tree' },
  { id: 'waldruh-west-tree-01', asset: 'cypress', x: 37, y: 237, width: 115, motion: 'tree' },
  { id: 'waldruh-west-tree-02', asset: 'tree', frame: 'tree-3', variant: true, x: 49, y: 335, width: 124, motion: 'tree', flipX: true },
  { id: 'waldruh-west-tree-03', asset: 'tree', frame: 'tree-4', variant: true, x: 53, y: 456, width: 134, motion: 'tree' },
  { id: 'waldruh-west-tree-04', asset: 'cypress', x: 321, y: 517, width: 91, motion: 'tree' },
  { id: 'waldruh-west-tree-05', asset: 'tree', frame: 'tree-1', variant: true, x: 65, y: 727, width: 140, motion: 'tree', flipX: true },
  { id: 'waldruh-west-tree-06', asset: 'cypress', x: 136, y: 806, width: 135, motion: 'tree' },
  { id: 'waldruh-west-tree-07', asset: 'tree', frame: 'tree-2', variant: true, x: 53, y: 936, width: 164, motion: 'tree' },
  { id: 'waldruh-south-tree-01', asset: 'tree', x: 147, y: 1013, width: 186, motion: 'tree' },
  { id: 'waldruh-south-tree-02', asset: 'tree', frame: 'tree-4', variant: true, x: 293, y: 998, width: 140, motion: 'tree', flipX: true },
  { id: 'waldruh-south-tree-03', asset: 'cypress', x: 517, y: 1030, width: 156, motion: 'tree' },
  { id: 'waldruh-south-tree-04', asset: 'tree', frame: 'tree-1', variant: true, x: 484, y: 898, width: 119, motion: 'tree' },
  { id: 'waldruh-south-tree-05', asset: 'tree', frame: 'tree-2', variant: true, x: 828, y: 982, width: 186, motion: 'tree', flipX: true },
  { id: 'waldruh-south-tree-06', asset: 'cypress', x: 956, y: 1030, width: 157, motion: 'tree' },
  { id: 'waldruh-south-tree-07', asset: 'tree', frame: 'tree-3', variant: true, x: 920, y: 979, width: 145, motion: 'tree' },
  { id: 'waldruh-garden-tree-01', asset: 'tree', x: 1197, y: 902, width: 123, motion: 'tree' },
  { id: 'waldruh-garden-tree-02', asset: 'tree', frame: 'tree-1', variant: true, x: 1298, y: 823, width: 89, motion: 'tree', flipX: true },
  { id: 'waldruh-east-tree-01', asset: 'cypress', x: 1507, y: 205, width: 107, motion: 'tree' },
  { id: 'waldruh-east-tree-02', asset: 'tree', frame: 'tree-2', variant: true, x: 1518, y: 360, width: 124, motion: 'tree', flipX: true },
  { id: 'waldruh-east-tree-03', asset: 'tree', frame: 'tree-3', variant: true, x: 1510, y: 550, width: 117, motion: 'tree' },
  { id: 'waldruh-east-tree-04', asset: 'cypress', x: 1480, y: 918, width: 134, motion: 'tree' },
];
