import type { PlacedScenerySpec } from './placed-scenery';

// The terrain contains roads and water only. Every raised object below has its
// own transparent frame, foot anchor, draw order and independent animation.
export const lindenhafenPlacements: readonly PlacedScenerySpec[] = [
  // Landmarks keep the archive, café, railway and workshop beside their cast.
  { id: 'archive', asset: 'archive', x: 203, y: 317, width: 290, motion: 'building' },
  { id: 'cafe', asset: 'cafe', x: 588, y: 455, width: 332, motion: 'building' },
  { id: 'station', asset: 'station', x: 1325, y: 286, width: 430, motion: 'building' },
  { id: 'workshop', asset: 'workshop', x: 259, y: 725, width: 324, motion: 'building' },
  { id: 'riverside-house', asset: 'house', frame: 'house-1', variant: true, x: 1161, y: 819, width: 231, motion: 'building' },
  { id: 'west-edge-house', asset: 'house', frame: 'house-2', variant: true, x: 4, y: 236, width: 124, motion: 'building', flipX: true },
  { id: 'north-library-house', asset: 'house', frame: 'house-3', variant: true, x: 94, y: 87, width: 153, motion: 'building' },
  { id: 'north-central-house', asset: 'house', frame: 'house-4', variant: true, x: 371, y: 103, width: 167, motion: 'building', flipX: true },
  { id: 'high-street-house', asset: 'house', frame: 'house-1', variant: true, x: 650, y: 176, width: 185, motion: 'building' },
  { id: 'high-street-east-house', asset: 'house', frame: 'house-2', variant: true, x: 875, y: 157, width: 191, motion: 'building', flipX: true },
  { id: 'high-street-cottage', asset: 'house', frame: 'house-3', variant: true, x: 776, y: 217, width: 107, motion: 'building' },
  { id: 'workshop-west-house', asset: 'house', frame: 'house-4', variant: true, x: 42, y: 623, width: 167, motion: 'building', flipX: true },
  { id: 'east-canal-house', asset: 'house', frame: 'house-1', variant: true, x: 1520, y: 842, width: 168, motion: 'building' },
  { id: 'southwest-canal-house', asset: 'house', frame: 'house-2', variant: true, x: 92, y: 1083, width: 238, motion: 'building', flipX: true },

  // Separate crowns sway from trunk anchors around the blocked building plots.
  { id: 'archive-west-tree', asset: 'tree', frame: 'tree-1', variant: true, x: 45, y: 285, width: 105, motion: 'tree' },
  { id: 'archive-back-tree', asset: 'tree', frame: 'tree-2', variant: true, x: 337, y: 196, width: 157, motion: 'tree' },
  { id: 'archive-east-tree', asset: 'tree', frame: 'tree-3', variant: true, x: 405, y: 283, width: 144, motion: 'tree', flipX: true },
  { id: 'archive-north-tree', asset: 'tree', frame: 'tree-4', variant: true, x: 281, y: 61, width: 132, motion: 'tree' },
  { id: 'cafe-back-tree', asset: 'tree', x: 512, y: 219, width: 118, motion: 'tree' },
  { id: 'cafe-north-tree', asset: 'tree', frame: 'tree-2', variant: true, x: 462, y: 107, width: 126, motion: 'tree', flipX: true },
  { id: 'cafe-east-tree', asset: 'tree', frame: 'tree-3', variant: true, x: 717, y: 303, width: 92, motion: 'tree' },
  { id: 'high-street-tree', asset: 'tree', frame: 'tree-4', variant: true, x: 853, y: 229, width: 111, motion: 'tree', flipX: true },
  { id: 'high-street-north-tree', asset: 'tree', frame: 'tree-1', variant: true, x: 1013, y: 110, width: 133, motion: 'tree' },
  { id: 'station-garden-tree', asset: 'tree', x: 1080, y: 159, width: 85, motion: 'tree' },
  { id: 'market-north-tree', asset: 'tree', frame: 'tree-3', variant: true, x: 945, y: 345, width: 154, motion: 'tree', flipX: true },
  { id: 'market-east-tree', asset: 'tree', frame: 'tree-4', variant: true, x: 1157, y: 379, width: 106, motion: 'tree' },
  { id: 'market-west-tree', asset: 'tree', frame: 'tree-1', variant: true, x: 874, y: 470, width: 72, motion: 'tree' },
  { id: 'workshop-back-tree', asset: 'tree', frame: 'tree-2', variant: true, x: 309, y: 569, width: 129, motion: 'tree', flipX: true },
  { id: 'workshop-garden-tree', asset: 'tree', x: 494, y: 606, width: 80, motion: 'tree' },
  { id: 'rose-garden-north-tree', asset: 'tree', frame: 'tree-4', variant: true, x: 741, y: 699, width: 72, motion: 'tree' },
  { id: 'rose-garden-east-tree', asset: 'tree', frame: 'tree-1', variant: true, x: 976, y: 733, width: 84, motion: 'tree', flipX: true },
  { id: 'rose-garden-south-tree', asset: 'tree', frame: 'tree-2', variant: true, x: 649, y: 980, width: 96, motion: 'tree' },
  { id: 'south-canal-tree', asset: 'tree', frame: 'tree-3', variant: true, x: 289, y: 1017, width: 114, motion: 'tree' },
  { id: 'riverside-door-tree', asset: 'tree', x: 1043, y: 767, width: 77, motion: 'tree' },
  { id: 'east-canal-tree', asset: 'tree', frame: 'tree-1', variant: true, x: 1476, y: 1010, width: 119, motion: 'tree', flipX: true },
  { id: 'west-canal-tree', asset: 'tree', frame: 'tree-2', variant: true, x: 75, y: 828, width: 104, motion: 'tree' },
  { id: 'archive-garden-cypress', asset: 'cypress', x: 356, y: 430, width: 38, motion: 'tree' },
  { id: 'workshop-street-cypress', asset: 'cypress', x: 595, y: 609, width: 29, motion: 'tree' },
  { id: 'workshop-garden-cypress', asset: 'cypress', x: 422, y: 570, width: 43, motion: 'tree' },
  { id: 'rose-garden-east-cypress', asset: 'cypress', x: 833, y: 822, width: 57, motion: 'tree' },
  { id: 'rose-garden-west-cypress', asset: 'cypress', x: 531, y: 774, width: 40, motion: 'tree' },

  // Lamp bases follow the old street edges, leaving the middle of each lane clear.
  { id: 'archive-front-lamp', asset: 'lamp', x: 158, y: 413, width: 32, motion: 'lamp' },
  { id: 'archive-east-lamp', asset: 'lamp', x: 338, y: 373, width: 27, motion: 'lamp' },
  { id: 'archive-garden-lamp', asset: 'lamp', x: 375, y: 433, width: 26, motion: 'lamp' },
  { id: 'cafe-west-lamp', asset: 'lamp', x: 525, y: 459, width: 27, motion: 'lamp' },
  { id: 'cafe-east-lamp', asset: 'lamp', x: 763, y: 383, width: 27, motion: 'lamp' },
  { id: 'workshop-rose-lamp', asset: 'lamp', x: 578, y: 605, width: 28, motion: 'lamp' },
  { id: 'rose-garden-north-lamp', asset: 'lamp', x: 675, y: 663, width: 29, motion: 'lamp' },
  { id: 'rose-garden-east-lamp', asset: 'lamp', x: 797, y: 733, width: 31, motion: 'lamp' },
  { id: 'rose-garden-gate-lamp', asset: 'lamp', x: 752, y: 882, width: 34, motion: 'lamp' },
  { id: 'southwest-bridge-lamp', asset: 'lamp', x: 459, y: 898, width: 32, motion: 'lamp' },
  { id: 'market-west-lamp', asset: 'lamp', x: 878, y: 321, width: 28, motion: 'lamp' },
  { id: 'high-street-garden-lamp', asset: 'lamp', x: 853, y: 236, width: 26, motion: 'lamp' },
  { id: 'high-street-east-lamp', asset: 'lamp', x: 912, y: 220, width: 26, motion: 'lamp' },
  { id: 'market-north-lamp', asset: 'lamp', x: 1098, y: 320, width: 23, motion: 'lamp' },
  { id: 'market-east-lamp', asset: 'lamp', x: 1238, y: 454, width: 31, motion: 'lamp' },
  { id: 'riverside-bridge-lamp', asset: 'lamp', x: 1216, y: 591, width: 27, motion: 'lamp' },
  { id: 'southeast-bridge-lamp', asset: 'lamp', x: 1413, y: 937, width: 33, motion: 'lamp' },
  { id: 'river-middle-bridge-lamp', asset: 'lamp', x: 1480, y: 572, width: 39, motion: 'lamp' },
  { id: 'station-forecourt-lamp', asset: 'lamp', x: 1208, y: 300, width: 30, motion: 'lamp' },
  { id: 'south-canal-crossing-lamp', asset: 'lamp', x: 911, y: 975, width: 31, motion: 'lamp' },

  // Cloth and water animate independently around the open square.
  { id: 'market-west-stall', asset: 'stall', frame: 'stall-1', variant: true, x: 928, y: 495, width: 102, motion: 'cloth' },
  { id: 'market-south-stall', asset: 'stall', frame: 'stall-2', variant: true, x: 1038, y: 524, width: 112, motion: 'cloth', flipX: true },
  { id: 'market-east-stall', asset: 'stall', frame: 'stall-3', variant: true, x: 1151, y: 458, width: 98, motion: 'cloth' },
  { id: 'market-middle-stall', asset: 'stall', frame: 'stall-4', variant: true, x: 1057, y: 398, width: 104, motion: 'cloth', flipX: true },
  { id: 'market-north-stall', asset: 'stall', frame: 'stall-1', variant: true, x: 961, y: 403, width: 94, motion: 'cloth' },
  { id: 'workshop-canopy', asset: 'stall', frame: 'stall-2', variant: true, x: 416, y: 711, width: 75, motion: 'cloth', flipX: true },
  { id: 'square-fountain', asset: 'fountain', x: 818, y: 567, width: 106, motion: 'water' },
  { id: 'garden-fountain', asset: 'fountain', x: 688, y: 796, width: 93, motion: 'water' },
  { id: 'rose-garden-arch', asset: 'arch', x: 640, y: 708, width: 135, motion: 'cloth' },
  { id: 'archive-garden-arch', asset: 'arch', x: 244, y: 430, width: 87, motion: 'cloth' },
  { id: 'rose-garden-greenhouse', asset: 'greenhouse', x: 855, y: 862, width: 97, motion: 'building' },

  // Furniture, planting and signs are reusable objects with their own bases.
  { id: 'archive-west-bench', asset: 'bench', x: 102, y: 361, width: 48, motion: 'still' },
  { id: 'workshop-bench', asset: 'bench', x: 555, y: 630, width: 49, motion: 'still', flipX: true },
  { id: 'rose-garden-east-bench', asset: 'bench', x: 771, y: 770, width: 43, motion: 'still' },
  { id: 'rose-garden-west-bench', asset: 'bench', x: 572, y: 777, width: 46, motion: 'still', flipX: true },
  { id: 'station-forecourt-bench', asset: 'bench', x: 1150, y: 253, width: 49, motion: 'still' },
  { id: 'garden-south-bench', asset: 'bench', x: 583, y: 887, width: 43, motion: 'still' },
  { id: 'cafe-east-planter', asset: 'planter', frame: 'planter-1', variant: true, x: 779, y: 407, width: 31, motion: 'tree' },
  { id: 'workshop-front-planter', asset: 'planter', frame: 'planter-2', variant: true, x: 515, y: 648, width: 36, motion: 'tree' },
  { id: 'station-street-planter', asset: 'planter', frame: 'garden-1', variant: true, x: 1289, y: 328, width: 31, motion: 'still' },
  { id: 'archive-front-planter', asset: 'planter', frame: 'garden-2', variant: true, x: 306, y: 304, width: 31, motion: 'still' },
  { id: 'garden-west-planter', asset: 'planter', frame: 'planter-1', variant: true, x: 463, y: 807, width: 31, motion: 'tree' },
  { id: 'garden-northeast-planter', asset: 'planter', frame: 'planter-2', variant: true, x: 907, y: 801, width: 30, motion: 'tree' },
  { id: 'garden-south-planter', asset: 'planter', frame: 'garden-1', variant: true, x: 761, y: 933, width: 30, motion: 'still' },
  { id: 'riverside-planter', asset: 'planter', frame: 'garden-2', variant: true, x: 1027, y: 848, width: 38, motion: 'still' },
  { id: 'market-crate-planter', asset: 'planter', frame: 'planter-1', variant: true, x: 1106, y: 521, width: 32, motion: 'tree' },
  { id: 'northern-bridge-planter', asset: 'planter', frame: 'planter-2', variant: true, x: 1453, y: 387, width: 34, motion: 'tree' },
  { id: 'cafe-menu', asset: 'sign', x: 650, y: 487, width: 29, motion: 'still' },
  { id: 'station-departure-sign', asset: 'sign', x: 1266, y: 339, width: 38, motion: 'still' },
  { id: 'workshop-direction-sign', asset: 'sign', x: 391, y: 736, width: 29, motion: 'still' },
  { id: 'south-garden-sign', asset: 'sign', x: 873, y: 926, width: 30, motion: 'still' },

  // Floating objects occupy canal water, clear of all bridge walking decks.
  { id: 'west-canal-rowboat', asset: 'boat', x: 225, y: 838, width: 85, motion: 'boat' },
  { id: 'south-canal-rowboat', asset: 'boat', x: 479, y: 1000, width: 82, motion: 'boat', flipX: true },
  { id: 'east-canal-rowboat', asset: 'boat', x: 1348, y: 802, width: 70, motion: 'boat' },
  { id: 'north-canal-rowboat', asset: 'boat', x: 1489, y: 480, width: 65, motion: 'boat', flipX: true },
];
